#!/bin/bash
# @file: jlink_client
# Copyrights (C) 2019, Shubham Patil <shubhampatil.patil@gmail.com>
#

source jlink_common

DBG_FLAG=0
# Array to store debugger IDs
IDs=()

log_debug()
{
	if [ $DBG_FLAG -eq 1 ]
	then
		echo $@
	fi
}

fill_ids()
{
	local id_output=`nrflist`

	if [[ $id_output ]];
	then
		for id in $id_output
		do
			IDs+=( $id )
		done
	else
		echo "No debugger connected to the PC"
		return 1
	fi
}

validate_args()
{
	if ! is_number $1
	then
		log_debug "$1 not a number"
		return 1
	fi

	if ! fill_ids
	then
		return 2
	fi

	if [ $1 -lt ${#IDs[*]} ] && [ $1 -lt ${#RTTPORT[*]} ]
	then
		return 0
	else
		return 1
	fi
}

cmd_run()
{
	jlink-server -SelectEmuBySN ${IDs[$1]} -RTTTelnetPort ${RTTPORT[$1]}
}

jlink_server()
{
	validate_args $1
	local rc=$?
	
	if [ $rc -eq 0 ]
	then
		cmd_run $1
	elif [ $rc -eq 2 ]
	then
		return 0
	else
		show_help
		return 1
	fi
}

# TODO: convert to switch case 
main()
{
	if [ $# -eq 0 ]
	then
		jlink_server 0
	elif [ $# -eq 1 ]
	then
		jlink_server $1
	else
		show_help
	fi
}

main $@

